# Generated by Django 2.2.5 on 2019-09-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphabet',
            old_name='question_text',
            new_name='alphabet_text',
        ),
    ]
